name: textplorer-ci/cd-pipeline

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install NLTK and download punkt resource
        run: |
          pip install nltk
          python -m nltk.downloader punkt stopwords

      - name: Set AWS environment variables
        run: |
          echo "export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "export AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV
          echo "export DYNAMODB_TABLE_NAME=${{ secrets.DYNAMODB_TABLE_NAME }}" >> $GITHUB_ENV


          - name: Run  tests
            run: |
              python -m unittest src.tests.test_data_collection src.tests.integration_test_routes src.tests.unit_and_mock_test_analysis src.tests.unit_and_mock_test_database
          #          python -m unittest discover -s src/tests

          - name: Deploy to Heroku
            if: success()
            uses: akhileshns/heroku-deploy@v3.13.15 # This is the actions
            with:
              heroku_api_key: ${{secrets.HEROKU_API_KEY}}
              heroku_app_name: "textplorer-256f19cfa476"
              heroku_email: ${{ secrets.HEROKU_EMAIL }}
              healthcheck: "https://textplorer-256f19cfa476.herokuapp.com/health_check"
