name: textplorer-ci/cd-pipeline

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run  tests
        run: |
          python -m unittest discover -s tests

      - name: Deploy to Heroku
        if: success()
        uses: akhileshns/heroku-deploy@3.13.15 # This is the actions
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "textplorer-256f19cfa476"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          healthcheck: "https://textplorer-256f19cfa476.herokuapp.com/health_check"
